type: blue
# TRODKROPH
An ancient myrh creature. It looks
-xtremely powerful yet friendly.
Fire Damage Bonus +85%
'WHERN ENEMIES DIiE THEIR CORPSE HAS A
CHANCE To EXPLODE DEALING FiRE
DAmAGE.
YOUR DRAGONLING USES iTS mAGiC TO
DIRECTLY PICK UP ALL LOOT BAGS.
FiRE ABILITIES WiLL ALSO BENEFIT FROM
LiGHTninG sonus.
窶呂HANCE TO SPAWN AN AURA NEAR YOU,
ENTERING THis AURA GRANTS YOU FiRE
DAmAGE BUFF
窶賂AiN ADDITIONAL 1% DAMAGE BONUS FOR
EACH EXTRA INVENTORY SLOT
AFTER A DASH CAUSE A FiRE EXPLOSION AND
GAIN BONUS FIRE DAMAGE FOR A SHORT
Duration.
